image: node:10.15.0
clone:
  depth: full

pipelines:
  default:
    - step:
        name: Build and test
        script:
          - npm install
          - npm test
          - apt-get update
          - apt-get install tar
          - tar czfv build-$BITBUCKET_BUILD_NUMBER.tgz $BITBUCKET_CLONE_DIR -C / -T
        artifacts: 
          - build-*.tgz
    - step:
        name: Deploy to Production
        deployment: production
        caches:
          - node
        script:
          - pipe: atlassian/heroku-deploy:1.2.1
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              ZIP_FILE: build-$BITBUCKET_BUILD_NUMBER.tgz