image: node:10.15.0
clone:
  depth: full

pipelines:
  default:
    - step:
        name: Build and test
        script:
          - npm install
          - npm test
          - npm run build
          - sudo apt-get update
          - sudo apt-get install zip
          - zip -r build-$BITBUCKET_BUILD_NUMBER.zip .
        artifacts: 
          - build-*.zip
    - step:
        name: Deploy to Production
        deployment: production
        caches:
          - node
        script:
          - pipe: atlassian/heroku-deploy:1.2.1
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              ZIP_FILE: build-$BITBUCKET_BUILD_NUMBER.zip