image: node:10.15.0
clone:
  depth: full
  
pipelines:
  default:
    - step:
        name: Deploy to production
        deployment: production
        caches:
          - node
        script:
          - pipe: atlassian/heroku-deploy:1.2.1
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              ZIP_FILE: achievementroadmaps/GoneAway-achievementroadmaps-299316ca764b.zip